name: Cypress Tests
on:
  pull_request:
  workflow_dispatch:

concurrency: cypress-ui
  
jobs:
  cypress-ui:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Cypress run
      uses: cypress-io/github-action@v5
      timeout-minutes: 5
      with:    
        config-file: ./cypress.config.js     
        spec: ./cypress/e2e/testingFeatures.js
        browser: chrome
        record: false
        start: npm run e2e:cypress:run
    
    - name: Upload test files
      uses: actions/upload-artifact@v3
      if: failure()
      with:
          name: cypress-screenshots
          path: ./cypress/screenshots
